<?php /* Smarty version 2.6.20, created on 2013-10-04 15:47:00
         compiled from header.tpl */

$this->_cache_serials['/home/meetuniv/public_html/video/Smarty/templates_c/%%F7^F7F^F7F34188%%header.tpl.inc'] = 'ff858e9814d081b355ad9f9e85fb59e3';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'dropdown_menu_video_categories', 'header.tpl', 145, false),array('function', 'dropdown_menu_article_categories', 'header.tpl', 153, false),)), $this); ?>
<?php
function _smarty_tplfunc_ff858e9814d081b355ad9f9e85fb59e3_0(&$_smarty)
{
echo smarty_art_html_list_categories(array(), $_smarty);
}



?>
